name: build-test
on:
  pull_request:
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test
      - run: npm run lint
      - run: npm run format:check
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dispatch and return Run ID
        id: return_dispatch
        uses: Codex-/return-dispatch@main
        with:
          token: ${{ secrets.TOKEN }}
          ref: ${{ github.ref }}
          repo: return-dispatch
          owner: codex-
          workflow: dispatch.yml
          workflow_inputs: "{\"cake\":\"delicious\"}"
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: ./
        with:
          token: ${{ github.token }}
          repo: return-dispatch
          owner: codex-
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
