name: build-test
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: test
        id: test
        if: ${{ always() }}
        run: npm run test
      - name: lint
        if: ${{ always() }}
        run: npm run lint
      - name: style
        if: ${{ always() }}
        run: npm run format:check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dispatch and return Run ID
        id: return_dispatch
        uses: Codex-/return-dispatch@main
        with:
          token: ${{ secrets.TOKEN }}
          ref: ${{ github.ref }}
          repo: return-dispatch
          owner: codex-
          workflow: dispatch.yml
          workflow_inputs: "{\"cake\":\"delicious\"}"
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: ./
        with:
          token: ${{ github.token }}
          repo: return-dispatch
          owner: codex-
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
  codecov: # Send only a single coverage report per run
    needs: [build, test]
    timeout-minutes: 15
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - name: test
        run: npm run test -- --coverage
      - name: codecov
        uses: codecov/codecov-action@v2
